### ISSUE TITLE
Add Points of Interest to iD

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/CrowdiD#1]
Can't edit Points of Interest... not all businesses are polygons, some of them are points.

![image](https://cloud.githubusercontent.com/assets/550895/19286055/4ec2e3dc-8fca-11e6-9f0c-6c3dce6927da.png)

**Image** Can't select Metro.

**Comment by Monduiz** [comment]
Modified the code in map_data.js to include points. Im closing this one.

**Comment by Monduiz** [comment]
Does this fix the issue?
