### ISSUE TITLE
Only navbar loads on mobile / iPad.

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/CrowdiD#4]
<a href="https://github.com/Monduiz"><img src="https://avatars.githubusercontent.com/u/8759714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Monduiz](https://github.com/Monduiz)**
_Sunday Oct 16, 2016 at 13:45 GMT_
_Originally opened as https://github.com/osmottawa/CrowdiD_archive/issues/7_

---

The main app doesnt appear on mobile or iPad. Possibly because of the popup first implementation.

**Comment by Monduiz** [comment]
With new version, loads on iPad. iD's UI is not really designed for touch though but the app works.
