### ISSUE TITLE
Add points: no form to enter attributes

### ISSUE THREAD

**Issue by Monduiz** [osmottawa/CrowdiD#5]
When a point is added, no form appears to enter attributes for it.

**Comment by Monduiz** [comment]
After some testing, the difference with a new point added on the map is in the panelwrap div. It receives a style="right: -100%". Other elements have "right: 0%".

**Comment by Monduiz** [comment]
This is now a huge priority

**Comment by DenisCarriere** [comment]
Looks like your update fixed it.

![image](https://cloud.githubusercontent.com/assets/550895/19412437/3cc3ab5e-92e4-11e6-9159-575535acf0fb.png)

**Comment by Monduiz** [comment]
Did it? When you add a new point, do you get a form to fill it with attributes?

**Comment by Monduiz** [comment]
When a new point is added, you cant enter the attributes. There is no form nor any way to select options to fill.

**Comment by Monduiz** [comment]
This is very odd. By playing with the styling in console, the form shows up. To fill it you have to search the feature.
![screen shot 2016-10-15 at 5 20 12 pm](https://cloud.githubusercontent.com/assets/8759714/19413482/0f3365aa-931e-11e6-8a00-a0b70c80ead7.png)

**Comment by Monduiz** [comment]
Fixed. Modified the preset_list accordingly. It should work now.
